version: '3'
services:
  jenkins:
    image: jenkins/jenkins:latest
    restart: always
#   environment:
#      JENKINS_JAVA_OPTIONS: "-Djava.awt.headless=true -Dmail.smtp.starttls.enable=true"
    ports:
    - 8888:8080
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
    - jenkins-volume:/var/jenkins_home
    - /etc/timezone:/etc/timezone 
    logging:
      driver: json-file
      options:
        max-size: 5m
        max-file: '5'
volumes:
  jenkins-volume: {}
